# Copyright 2025 Braden Ganetsky
# Distributed under the Boost Software License, Version 1.0.
# https://www.boost.org/LICENSE_1_0.txt

name: ci

on:
  workflow_dispatch:
  push:

jobs:
  msc_full_ver_test:
    strategy:
      matrix:
        include:
          # Check a random assortment of versions
          - {vs-version: "17.13.3",  msc-full-ver: "194334809"}

    runs-on: windows-2025
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: k3DW/setup-msvc@cache
        with:
          vs-version: "${{ matrix.vs-version }}"

      - name: Build the tests
        run: |
          cd tests
          mkdir build
          if ("${{ matrix.vs-version }}".StartsWith("16.")) {
            cmake . -B build -G "Visual Studio 16 2019"
          } elseif ("${{ matrix.vs-version }}".StartsWith("17.")) {
            cmake . -B build -G "Visual Studio 17 2022"
          } else {
            Write-Host "Currently only VS 2019 and VS 2022 are supported in testing"
            exit 1
          }
          cmake --build build --target msc_full_ver

      - name: Run the tests
        run: |
          cd tests
          & .\build\Debug\msc_full_ver.exe ${{ matrix.msc-full-ver }}
